### PR TITLE
Add new kernel hardening checkers and a comment section to the Kernel Config Analyzer

### PR DESCRIPTION
**Pull request by hammadahmedirdeto**
This adds new kernel hardening checkers and a comment section to the Kernel Config Analyzer (KCA) plugin.

The Kernel Config Analyzer (KCA) plugin in the Intel Static Analyzer Framework (ISAFW) does not provide any justification for its kernel configuration recommendations. A comment section has been added to the report. Hardening checkers from Irdeto's Kernel Hardening Guide have been added, increasing hardening checker coverage by 100%. 

Based on pull request 6.
https://github.com/01org/isafw/pull/6

Related discussion:
- https://lists.linuxfoundation.org/pipermail/automotive-discussions/2016-August/002438.html
- https://lists.linuxfoundation.org/pipermail/automotive-discussions/2016-May/001981.html
- https://jira.automotivelinux.org/browse/SPEC-118

### CODE REVIEW

**Comment by ereshetova** [comment]
This one has an issue with module referencing:

elena@elena-ThinkPad-X230:~/Python/isafw/tests$ python KCAPluginTestCase.py
Exception in plugin ISA_KernelChecker process_kernel():
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/isafw/isafw.py", line 134, in call_plugins
    method(_parameters, *_keywords)
  File "/usr/local/lib/python2.7/dist-packages/isaplugins/ISA_kca_plugin.py", line 324, in process_kernel
    return KCAnalyzer.process_kernel(ISA_kernel)
  File "/usr/local/lib/python2.7/dist-packages/isaplugins/ISA_kca_plugin.py", line 61, in process_kernel
    common_config_module = importlib.import_module('isafw.isaplugins.configs.kca.{}'.format('common'))
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named isaplugins.configs.kca.common

**Comment by mgreshis** [comment]
@ereshetova, could you please verify /usr/local/lib/python2.7/dist-packages/isaplugins/configs/kca/common.py exists after performing the pull? I double checked it appears on the change list for the pull request but your logs show the file is not there.

**Comment by mgreshis** [comment]
I can verify the **setup.py** is missing **configs/kca/***. The file is available in the pull request, but was never added to deployment.

**Comment by hammadahmedirdeto** [comment]
Updated with fix

**Comment by ereshetova** [comment]
It still has the same issue. The problem is that currently configs directory is marked as data in setup.py and not suppose to have executable code, so it creates issues with imports and etc. I am trying to see what is the best way to do this now

**Comment by ereshetova** [comment]
Turns out automatic resolving of packages from setup.py does the trick. Will merge this and the fix to setup.py.

**Pull request merged**
